services:
  - type: web
    name: vidma-backend
    runtime: dotnet|8
    rootDir: vidma-backend/VidmaEngineering
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/VidmaEngineering.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__Default
        sync: false
